baseURL = 'https://example.org/'
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
pagination.pagerSize     = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "A simple and beautiful blog"

  enableThemeToggle = true

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  avatar="/images/mia-foto.jpg"

[params.author]
  name = "Bernardo Trotta"
  
[params.footer]
    trademark = 2026
    rss = false
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
    ]

[params.Portrait]
  Path = "/images/mia-foto.jpg"
  Alt = "Bernardo Trotta"
  MaxWidth = "150px"

[[params.social]]
  name = "github"
  url = "https://github.com/bernardotrotta"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Hello Dude!"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "ciao a tutti, sono Bernardo Trotta e benvenuti sul mio fantastico sito"

    [languages.en.params.logo]
      logoText = "Bernardo Trotta"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  # and submenus
  [[menu.main]]
    identifier  = "parent"
    name        = "Parent"
    url         = "/parent"
    hasChildren = true

  [[menu.main]]
    identifier  = "child"
    name        = "Child"
    url         = "/parent/child"
    parent      = "parent"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
